---
title: 'Latentcor: An R Package for Latent Correlation Estimation'
tags:
- R
- Statistics
- Latent Correlation
date: "18 May 2021"
output:
  rticles::joss_article: default
  rticles::joss_article(): default
authors:
- name: Mingze Huang
  orcid: 0000-0003-3919-1564
  affiliation: 1, 2
- name: Irina Gaynanova
  orcid: 0000-0000-0000-0000
  affiliation: 2
- name: Christian L. Muller
year: 2021
bibliography: paper.bib
affiliations:
- name: Department of Statistics, Texas A& M University
  index: 1
- name: Department of Economics, Texas A& M University
  index: 2
- name: Department of Statistics, University of Munich
  index: 3
csl: apa.csl
journal: JOSS
---

# Summary

The R package *latentcor* provides estimation for latent correlation with mixed data types (continuous, binary, truncated and ternary). Comparing to *MixedCCA*, which estimates latent correlation for canonical correlation analysis, our new package provides a standalone version for latent correlation estimation. Also we add new functionality for latent correlation between ternary/continous, ternary/binary, ternary/truncated and ternary/ternary cases.


Compare to MixedCCA, standalone, new functionality, memory footprint.

# Statement of need
Currently there is no standalone package dealing with latent correlation for mixed data type like we did in *latentcor*. The R package *stats* [@team2013r] have some functionality to calculate different type of correlations (Pearson, Kendall and Spearman). The R package *pcaPP* [@croux2013robust] provides a fast calculation for Kendall's \tau. The R package *MixedCCA* [@yoon2020sparse] have functionality for latent correlation estimation as an intermediate step for canonical correlation analysis on mixed data.
No package deal with latent correlation across mixed data type.

# Usage
 
 |Type | continuous | binary | truncated | ternary |
|-----|----------|
|continuous | @liu2009nonparanormal | @fan2017high | @yoon2020sparse | @quan2018rank |
|binary | @fan2017high | @fan2017high | @yoon2020sparse | @quan2018rank |
|truncated | @yoon2020sparse | @yoon2020sparse | @yoon2020sparse | This paper |
|ternary | @quan2018rank | @quan2018rank | This paper | @quan2018rank |
 
*Definition 1* Fan et al. (2017) considered the problem of estimating $\Sigma$ for the latent Gaussian copula model based on Kendall's $\tau$. Given the observed data $(X_{1j}, X_{1k}), ..., (X_{nj}, X_{nk})$ for variables $X_{j}$ and $X_{k}$, Kendall's $\tau$ is defined as
$$
\hat{\tau}_{jk}=\frac{2}{n(n-1)}\sum_{1\leq i <i'\leq n} sign(X_{ij}-X_{i'j})sign(X_{ik}-X_{i'k})
$$
*Theorem 1* Let $W_{1}\in\cal{R}^{p_1}$, $W_{2}\in\cal{R}^{p_2}$, $W_{3}\in\cal{R}^{p_3}$ be such that $W=(W_{1}, W_{2}, W_{3})\sim NPN(0,\Sigma,f)$ with $p=p_{1}+p_{2}+p_{3}$. Let $X=(X_{1}, X_{2}, X_{3})\in\cal{R}^{p}$ satisfy $X_{j}=W_{j}$ for $j=1,...,p_{1}$, $X_{j}=I(W_{j}>c_{j})$ for $j=p_{1}+1,...,p_{1}+p_{2}$ and $X_{j}=I(W_{j}>c_{j})W_{j}$ for $j=p_{1}+p_{2}+1,...,p$ with $\Delta_{j}=f(c_{j})$. The rank-based estimator of $\Sigma$ based on the observed $n$ realizations of $X$ is the matrix $\hat{R}$ with $\hat{r}_{jj}=1$, $\hat{r}_{jk}=\hat{r}_{kj}=F^{-1}(\hat{\tau}_{jk})$ with block structure
$$
\hat{R}=\left(\begin{array}
F^{-1}_{CC}(\hat{\tau})\hspace{.2in} F^{-1}_{CB}(\hat{\tau})\hspace{.2in} F^{-1}_{CT}(\hat{\tau})\\
F^{-1}_{BC}(\hat{\tau})\hspace{.2in} F^{-1}_{BB}(\hat{\tau})\hspace{.2in} F^{-1}_{BT}(\hat{\tau})\\
F^{-1}_{TC}(\hat{\tau})\hspace{.2in} F^{-1}_{TB}(\hat{\tau})\hspace{.2in} F^{-1}_{TT}(\hat{\tau})
\end{array}\right)
$$
 Describe the theorem states expected value of kendall tau = F(r). refer to table for reference of formula.
 A sentence to describe two methods: slow original vs interpolation.
 Table to show memory improvement compare to mixedCCA.
 Generate data for pairs.
 One example of original call, one for interpolation call.

# Rendered R Figures

# References
